# Generated by Django 4.2.10 on 2025-07-27 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProducto',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'categorias_productos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo_identificacion', models.CharField(max_length=8)),
                ('identificacion', models.CharField(max_length=20, unique=True)),
                ('nombre_completo', models.CharField(max_length=150)),
                ('correo_electronico', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'clientes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetalleOrden',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_unitario_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('porcentaje_iva_aplicado', models.DecimalField(decimal_places=2, max_digits=4)),
                ('comentarios', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'detalles_orden',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('posicion_x', models.IntegerField(blank=True, null=True)),
                ('posicion_y', models.IntegerField(blank=True, null=True)),
                ('rotacion', models.IntegerField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'mesas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MovimientoCaja',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo_movimiento', models.CharField(max_length=7)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion', models.TextField()),
                ('fecha_movimiento', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'movimientos_caja',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=6)),
                ('estado', models.CharField(max_length=9)),
                ('fecha_apertura', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ordenes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PagoVenta',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('metodo_pago', models.CharField(max_length=13)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('referencia', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'pagos_venta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('codigo_cabys', models.CharField(blank=True, max_length=13, null=True)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('porcentaje_iva', models.DecimalField(decimal_places=2, max_digits=4)),
                ('stock_actual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('controla_stock', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'productos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RegistroAnulacion',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('motivo', models.TextField()),
                ('fecha_anulacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'registros_anulacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_rol', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'roles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Salon',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'salones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SesionCaja',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_apertura', models.DateTimeField(blank=True, null=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('monto_apertura', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monto_cierre_efectivo_contado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('monto_cierre_dejado_en_caja', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_calculado_efectivo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_calculado_tarjeta', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_calculado_sinpe', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('diferencia', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('observaciones_cierre', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sesiones_caja',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_usuario', models.CharField(max_length=50, unique=True)),
                ('hash_contrasena', models.CharField(max_length=255)),
                ('nombre_completo', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'usuarios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo_documento', models.CharField(max_length=19)),
                ('consecutivo_hacienda', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('fecha_venta', models.DateTimeField(blank=True, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monto_iva', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_final', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'ventas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthToken',
            fields=[
                ('key', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='Key')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auth_token', to='autentificacion.usuario', verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Auth Token',
                'verbose_name_plural': 'Auth Tokens',
            },
        ),
    ]
