# Generated by Django 4.2.10 on 2025-08-20 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autentificacion', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthToken',
        ),
    ]
