# Generated by Django 4.2.10 on 2025-09-01 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_order_remove_product_stock_product_cabys_product_tax_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='identificator',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='sell_type',
            field=models.CharField(choices=[('MESA', 'Para Mesa'), ('LLEVAR', 'Para Llevar'), ('FACTURAR', 'Directa')], default='MESA', max_length=50),
        ),
    ]
