# Generated by Django 4.2.10 on 2025-09-01 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_tables_salons'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salons',
            name='table',
        ),
        migrations.RemoveField(
            model_name='tables',
            name='order',
        ),
        migrations.AddField(
            model_name='order',
            name='tables',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='core.tables'),
        ),
        migrations.AddField(
            model_name='tables',
            name='salon',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='core.salons'),
            preserve_default=False,
        ),
    ]
