# Generated by Django 4.2.10 on 2025-09-07 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_order_canceled'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='tables',
            new_name='table',
        ),
    ]
